# Lo necesario para ejecutar la aplicación en local
services:

  # PostgresSQL
  postgres-db:
    container_name: tienda-db_postgres
    image: postgres:12-alpine
    restart: always
    env_file: .env.prod
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./database/tienda.sql:/docker-entrypoint-initdb.d/tienda.sql
    networks:
      - tienda-network

  # MongoDB
  mongo-db:
    container_name: tienda-db_mongo
    image: mongo:5.0
    restart: always
    env_file: .env.prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/tienda.js:/docker-entrypoint-initdb.d/tienda.js:ro
    networks:
      - tienda-network

  # Servicio de la API REST
  tienda-api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tienda-api-rest
    restart: always
    env_file: .env.prod
    ports:
      - ${API_PORT}:3000
    volumes:
      - storage-dir:/app/storage-dir
      - ./cert:/app/cert
    networks:
      - tienda-network
    depends_on:
      - postgres-db
      - mongo-db

# Volume para guardar los datos de la api rest, como las imágenes
volumes:
  storage-dir:

# Red para conectar los contenedores (opcional)
networks:
  tienda-network:
    driver: bridge